### ISSUE TITLE
Demo gets stuck at loading icon

### ISSUE THREAD

**Issue by mstreit** [sgratzl/lineup_demos_source#1]
No interaction possible because of loading icon overlay.

https://sgratzl.github.io/lineup_demos/

Here is what I get in Chrome:
![image](https://cloud.githubusercontent.com/assets/4129755/20137922/b954e406-a67d-11e6-9ba0-79e8a9f9ab76.png)

**Comment by sgratzl** [comment]
new build -try again

**Comment by mstreit** [comment]
Nice, thanks!
