### ISSUE TITLE
first four columns should be frozen

### ISSUE THREAD

**Issue by sgratzl** [sgratzl/lineup_demos_source#17]
@mstreit commented on [Mon Sep 11 2017](https://github.com/Caleydo/taggle/issues/80)

all columns until label column should be frozen (not impacted by horizontal scrolling).

---

@alexsb commented on [Mon Sep 18 2017](https://github.com/Caleydo/taggle/issues/80#issuecomment-330367726)

More generally, I want to define columns that shouldn't scroll form the left, as is possible in google spreadsheets.

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/32946627-9e9f0376-cb98-11e7-9bd4-89afc2af187b.png)

**Comment by mstreit** [comment]
scales of numerical columns do not dissappear

![image](https://user-images.githubusercontent.com/4129755/32950025-27c13280-cba5-11e7-96d2-fc285ad35d44.png)

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/32951144-33a9400c-cba9-11e7-9bb0-f6cec43fe2f6.png)

in the background position: sticky is used. Thus the frozen columns are just overlaying the others. In the described case there was nothing to overlay the axis labels
