### ISSUE TITLE
Restore from Gist broken

### ISSUE THREAD

**Issue by sgratzl** [sgratzl/lineup_demos_source#18]
@mstreit commented on [Fri Nov 10 2017](https://github.com/Caleydo/lineupjs/issues/429)

* Release number or git hash: deployed
* Web browser version and OS: chrome

### Steps to reproduce

1. save to gist
2. take link and past it in second browser window

### Observed behavior
* Only one item is contained in the restored table.

### Expected behavior
* Same items as in stored table. 

![image](https://user-images.githubusercontent.com/4129755/32654125-69a002d0-c60a-11e7-913b-0cd9f56b15c4.png)

**Comment by mstreit** [comment]
Also the numerical values in the filter panel are not restored properly.

![image](https://user-images.githubusercontent.com/4129755/32654265-e141dc0a-c60a-11e7-95d6-07794e4d53ec.png)

**Comment by sgratzl** [comment]
fixed, e.g. http://localhost:8080/#gist:c8380f6028cf9d06bf5679bc02418446
