### ISSUE TITLE
Matrix stratification not restoring correctly from Gist

### ISSUE THREAD

**Issue by sgratzl** [sgratzl/lineup_demos_source#20]
@katush commented on [Mon Nov 20 2017](https://github.com/Caleydo/lineupjs/issues/470)

Matrix stratification not restoring correctly from Gist. Although the stratification is there, each stratified column contains all the matrix data (1990-2015) instead of 1990-1999, 2000-2010, 2010-2015.
![image](https://user-images.githubusercontent.com/8986080/32998040-d5c34046-cd97-11e7-88fc-b59108f5b9d4.png)
There were also missing stratification data for matrices when I tried to re-add and re-stratify them:
![image](https://user-images.githubusercontent.com/8986080/32998227-7b10a132-cd99-11e7-8148-91c65eb1afb2.png)

**Comment by thinkh** [comment]
Won't fix, since anonymous Gist support is not possible anymore and the Gist support is discontinued in the successor app.
