### ISSUE TITLE
Direct link to demo datasets with hashtags

### ISSUE THREAD

**Issue by sgratzl** [sgratzl/lineup_demos_source#5]
https://github.com/Caleydo/lineup.js/issues/100

tweet direct link to demo datasets with hashtags that make the respective target audience aware of the demo.

**Comment by thinkh** [comment]
Done with the successor [lineup_app](https://github.com/Caleydo/lineup_app). 

See: https://lineup.js.org/app/#soccer or https://lineup.js.org/app/#shanghai
